### ISSUE TITLE
Displaying month and years tables

### ISSUE THREAD

**Issue by Alex-Sokolov** [MakingSense/moment-datepicker#62]
Thanks for plugin!

But I found a small bug. Days view rendered ok, but when switch to month or years views:
![moment-datepicker](https://cloud.githubusercontent.com/assets/4497128/7471426/794acacc-f32f-11e4-92b1-75d38f5fb936.png)

Init plugin with:
```js
$('.calendar').datepicker({
	format: 'DD.MM.YYYY',
	weekStart: 1,
	language: 'ru'
});
```
After small investigation found a workaround:
```css
.datepicker.dropdown-menu .table-condensed {
  width: 100%;
}
```
Can you fix this in new version?

P.S.:
Use jquery 1.11.2, bootstrap 3.3.4, latest version of moment-datepicker
